import type { FilterPreset } from './types';

export const FILTER_PRESETS: FilterPreset[] = [
  {
    id: 'joy-golden',
    name: '金色时光',
    mood: 'joy',
    brightness: 1.1,
    contrast: 1.05,
    saturation: 1.2,
    hueRotate: 0,
    sepia: 0.1,
    blur: 0,
    temperature: 20,
    grain: 0,
    vignette: 0.15,
    overlayColor: '#FFD166',
    overlayOpacity: 0.05,
  },
  {
    id: 'melancholy-blue',
    name: '蓝调低语',
    mood: 'melancholy',
    brightness: 0.9,
    contrast: 1.1,
    saturation: 0.7,
    hueRotate: 200,
    sepia: 0,
    blur: 0,
    temperature: -30,
    grain: 0.08,
    vignette: 0.4,
    overlayColor: '#7B8CDE',
    overlayOpacity: 0.08,
  },
  {
    id: 'calm-sage',
    name: '薄荷微风',
    mood: 'calm',
    brightness: 1.05,
    contrast: 0.95,
    saturation: 0.85,
    hueRotate: 0,
    sepia: 0.05,
    blur: 0,
    temperature: -5,
    grain: 0,
    vignette: 0.1,
    overlayColor: '#88C9A1',
    overlayOpacity: 0.04,
  },
  {
    id: 'anxious-tense',
    name: '神经末梢',
    mood: 'anxious',
    brightness: 1.05,
    contrast: 1.25,
    saturation: 0.9,
    hueRotate: 0,
    sepia: 0,
    blur: 0,
    temperature: 10,
    grain: 0.15,
    vignette: 0.5,
    overlayColor: '#E07A5F',
    overlayOpacity: 0.06,
  },
  {
    id: 'nostalgic-sepia',
    name: '旧日胶片',
    mood: 'nostalgic',
    brightness: 1.0,
    contrast: 1.05,
    saturation: 0.6,
    hueRotate: 0,
    sepia: 0.4,
    blur: 0,
    temperature: 25,
    grain: 0.2,
    vignette: 0.35,
  },
  {
    id: 'excited-vivid',
    name: '心跳加速',
    mood: 'excited',
    brightness: 1.15,
    contrast: 1.15,
    saturation: 1.4,
    hueRotate: 0,
    sepia: 0,
    blur: 0,
    temperature: 10,
    grain: 0,
    vignette: 0.1,
    overlayColor: '#FF6B9D',
    overlayOpacity: 0.05,
  },
  {
    id: 'lonely-midnight',
    name: '深夜独白',
    mood: 'lonely',
    brightness: 0.85,
    contrast: 1.1,
    saturation: 0.5,
    hueRotate: 240,
    sepia: 0,
    blur: 0,
    temperature: -20,
    grain: 0.12,
    vignette: 0.5,
    overlayColor: '#9B8EC2',
    overlayOpacity: 0.07,
  },
  {
    id: 'grateful-warm',
    name: '暖意流转',
    mood: 'grateful',
    brightness: 1.1,
    contrast: 1.0,
    saturation: 1.1,
    hueRotate: 0,
    sepia: 0.15,
    blur: 0,
    temperature: 30,
    grain: 0,
    vignette: 0.2,
    overlayColor: '#F2CC8F',
    overlayOpacity: 0.06,
  },
  {
    id: 'dreamy-haze',
    name: '梦境边缘',
    mood: 'dreamy',
    brightness: 1.1,
    contrast: 0.9,
    saturation: 0.8,
    hueRotate: 280,
    sepia: 0.05,
    blur: 0.5,
    temperature: 5,
    grain: 0.05,
    vignette: 0.3,
    overlayColor: '#C8B6FF',
    overlayOpacity: 0.08,
  },
  {
    id: 'rebellious-raw',
    name: '生猛粗粝',
    mood: 'rebellious',
    brightness: 1.05,
    contrast: 1.35,
    saturation: 0.8,
    hueRotate: 0,
    sepia: 0,
    blur: 0,
    temperature: 0,
    grain: 0.25,
    vignette: 0.4,
    overlayColor: '#EF4444',
    overlayOpacity: 0.06,
  },
];

export function getPresetsForMood(mood: string): FilterPreset[] {
  return FILTER_PRESETS.filter((p) => p.mood === mood);
}

export function getPresetById(id: string): FilterPreset | undefined {
  return FILTER_PRESETS.find((p) => p.id === id);
}
